regions:
  - us-east-1

blocklist:
  - "999999999999"  # Example account to protect

accounts:
  "339713153871":   # Your account number
    presets:
      - defaults
    filters:
      IAMUser:
        - "admin"   # Protect your admin user
      IAMUserPolicyAttachment:
        - "admin -> AdministratorAccess"
      IAMUserAccessKey:
        - "admin -> *"

presets:
  defaults:
    filters:
      IAMRole:
        - type: glob
          value: "aws-service-role*"
        - type: glob
          value: "AWSServiceRole*"
